### ISSUE TITLE
Jumps (non smooth trajectory) upon calibration

### ISSUE THREAD

**Issue by MaximilienNaveau** [open-dynamic-robot-initiative/odri_control_interface#6]
This problem has been spotted on Bolt with a 50% chance of occurrence.
@majidkhadiv  if you want you can detail the seen behavior here.

In principle, upon calibration, the robot jumps into a certain position before it starts a smooth trajectory toward the desired index.

**Comment by jviereck** [comment]
@majidkhadiv can you upload a video of the behavior to get an idea what it looks like?

**Comment by majidkhadiv** [comment]
Sorry I forgot to elaborate on the problem here. I just figured out why this was happening. When we turn the power source on, we should not move the joints, because it seems that the starting point of the trajectory for finding the encoder index is zero and it does not set the starting point to the position of the encoder upon the call of the calibration command (this was the case with @MaximilienNaveau implementation). So now if we turn the power source on and move the joints and then call calibration, the joints will jump first to the point where the robot was when we turned the robot on and then it moves to find the index...

**Comment by jviereck** [comment]
No worries about taking some time to reply. Glad you figured it out in the meantime.

Is it a problem if you are not allowed to move the legs after power on? With the new firmware, the micro drivers track the first index they see for compensation and the PD controller. Therefore moving the legs after power on and doing the calibration later is problematic.

**Comment by majidkhadiv** [comment]
I don't think it is a problem, but good to know :) So we can now safely close this issue!

**Comment by jviereck** [comment]
Okay: ) Closing the issue.
